language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python 3.8.0 on Bionic Linux"
      dist: bionic
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    - name: "Linux ARMv8"
      arch: arm64
      dist: bionic
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.4 on macOS"
      os: osx
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install:
    - pip3 install --upgrade pip pyinstaller wheel
    - pip3 install -r requirements.txt .
script:
    - cd pyinstaller && ./bundle.sh
deploy:
  provider: releases
  api_key: $RELEASE_TOKEN
  file_glob: true
  file: deploy/*
  skip_cleanup: true
  draft: true
  on:
    tags: true
  name: $TRAVIS_TAG (DRAFT)
